import "./globals.css";
import "./reset.css";
import Header from "@/components/Header";
import { poppins } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
